Repository percona/pbm-docs, pull requests merged in 2025-02, with the labels that each got.

#254 Update configure-authentication.md
  docs/install/configure-authentication.md
Labels: enhancement

#220 Reworked PBM for user testing
  _resource/overrides/partials/header.html
  docs/details/authentication.md
  docs/details/versions.md
  docs/features/backup-sharding.md
  docs/features/comparison.md
  docs/features/incremental-backup.md
  docs/features/physical.md
  docs/features/point-in-time-recovery.md
  docs/features/restore-new-env.md
  docs/features/restore-remapping.md
  docs/features/selective-backup.md
  docs/features/snapshots.md
  docs/index.md
  docs/install/backup-storage.md
  docs/install/docker.md
  docs/install/start-pbm-agent.md
  docs/install/tarball.md
  docs/intro.md
  docs/manage/automate-s3-access.md
  docs/reference/config.md
  docs/reference/pbm-commands.md
  docs/release-notes/2.0.0.md
  docs/release-notes/2.0.4.md
  docs/release-notes/2.1.0.md
  docs/release-notes/2.2.0.md
  docs/release-notes/2.8.0.md
  docs/troubleshoot/status.md
  docs/troubleshoot/troubleshooting.md
  docs/usage/backup-external.md
  docs/usage/backup-incremental.md
  docs/usage/backup-physical.md
  docs/usage/backup-priority.md
  docs/usage/backup-selective.md
  docs/usage/compression.md
  docs/usage/list-backup.md
  docs/usage/logs.md
  docs/usage/oplog-replay.md
  docs/usage/pitr-physical.md
  docs/usage/pitr-selective.md
  docs/usage/pitr-tutorial.md
  docs/usage/restore-external.md
  docs/usage/restore-incremental.md
  docs/usage/restore-physical.md
  docs/usage/restore-progress.md
  docs/usage/restore-selective.md
  docs/usage/restore.md
  docs/usage/schedule-backup.md
  docs/usage/start-backup.md
  mkdocs-base.yml
  mkdocs.yml
  requirements.txt
  snippets/pitr-preparation.md
  snippets/prepare-backup.md
  snippets/restore-intro.md
Labels: do not merge, testing

#259 Igroene patch 3
  docs/usage/backup-incremental.md
  docs/usage/backup-physical.md
Labels: bug, documentation
